package:
  name: tophat
  version: 2.1.0

source:
  fn: tophat-2.1.0.Linux_x86_64.tar.gz
  url: http://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.0.Linux_x86_64.tar.gz
  md5: 0b525e8be75815c5dd745b49c379682c


build:
  number: 1

requirements:
  run:
    - python
    - bowtie2

test:
    commands:
        - (tophat --version 2>&1) > /dev/null

about:
  home: http://ccb.jhu.edu/software/tophat/index.shtml
  license: "Boost Software License, Version 1.0"
  license_file: LICENSE
  summary: 'TopHat is a fast splice junction mapper for RNA-Seq reads. It aligns RNA-Seq reads to mammalian-sized genomes using the ultra high-throughput short read aligner Bowtie, and then analyzes the mapping results to identify splice junctions between exons.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml


# ##############################################################

# # from https://anaconda.org/bioconda/tophat

# about:
#     home: 'http://ccb.jhu.edu/software/tophat/index.shtml'
#     license: Boost Software License
#     summary: A spliced read mapper for RNA-Seq
# package:
#     name: tophat
#     version: 2.1.0
# requirements:
#     build:
#         - python
#     run:
#         - python
# test:
#     commands:
#         - (tophat --version 2>&1) > /dev/null

# source:
#   fn: tophat-2.1.0.Linux_x86_64.tar.gz
#   url: http://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.0.Linux_x86_64.tar.gz
#   md5: 0b525e8be75815c5dd745b49c379682c

