package:
  name: bamtools
  version: 2.4.0

source:
  git_url: https://github.com/pezmaster31/bamtools.git
  git_tag: v2.4.0

build:
  number: 1

# requirements:
#   build:

#   run:


test:
  commands:
    - bamtools

about:
  home: https://github.com/pezmaster31/bamtools
  license: MIT
  license_file: LICENSE
  summary: "BamTools provides both a programmer's API and an end-user's toolkit for handling BAM files."