package:
  name: traitlets
  version: "4.0.0"

source:
  git_url: https://github.com/ipython/traitlets.git
  git_tag: 4.0.0


requirements:
  build:
    - python
    - ipython_genutils
    - decorator

  run:
    - python
    - ipython_genutils
    - decorator

test:
  imports:
    - traitlets



about:
  home: https://github.com/ipython/traitlets.git
  license: Custom
  license_file: COPYING.md
  summary: 'A lightweight pure-Python derivative of Enthought Traits, used for configuring Python objects. This package powers the config system of IPython and Jupyter.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml