package:
  name: pybioclim
  version: "0.0.1"

source:
  git_url: https://github.com/xguse/pybioclim.git
  git_tag: v0.0.1+xguse.fork
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tabulate = tabulate:main
    #
    # Would create an entry point called tabulate that calls tabulate.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gdal
    - gitpython
    - cython
    - matplotlib
    - basemap

  run:
    - python
    - numpy
    - gdal
    - gitpython
    - cython
    - matplotlib
    - basemap

test:
  # Python imports
  imports:
    - pybioclim

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/xguse/pybioclim.git
  license: custom
  summary: 'A Python interface to BIOCLIM climate data. Data files included in package. http://www.worldclim.org'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
