package:
  name: whichcraft
  version: "0.1.1"

source:
  fn: whichcraft-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/w/whichcraft/whichcraft-0.1.1.tar.gz
  md5: fb85ed3feebd330a8c46a101dad35dd6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - whichcraft = whichcraft:main
    #
    # Would create an entry point called whichcraft that calls whichcraft.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pydanny/whichcraft
  license: BSD License
  summary: 'This package provides cross-platform cross-python shutil.which functionality.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
