package:
  name: parallel
  version: 20150922

source:
  fn: parallel-20150922.tar.bz2
  url: http://gnu.mirror.iweb.com/parallel/parallel-20150922.tar.bz2
  md5: f2b485fabdca6492d892c57f50d112a7693f8dc088f74787c98eeb2aa11cee17

build:
  number: 1
  # string:

test:
  commands:
    - musqcle -version

about:
  home: http://www.gnu.org/software/parallel/
  license: GPL3
  summary: 'GNU parallel is a shell tool for executing jobs in parallel using one or more computers. A job can be a single command or a small script that has to be run for each of the lines in the input. The typical input is a list of files, a list of hosts, a list of users, a list of URLs, or a list of tables. A job can also be a command that reads from a pipe. GNU parallel can then split the input and pipe it into commands in parallel.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
