package:
  name: 4p
  version: 1.0

source:
  git_url: https://github.com/anbena/4p.git
  git_tag: 1.0


build:
  number: 1
  # string: 

# requirements:


test:
  commands:
    - 4P -h

about:
  home: https://github.com/anbena/4p
  license: GPL3
  license_file: COPYING
  summary: '4P (Parallel Processing of Polymorphism Panels) is a software for computing population genetics statistics from large SNPs dataset.'