package:
  name: picard
  version: 1.140

source:
  git_url: https://github.com/broadinstitute/picard.git
  git_tag: 1.140


build:
  number: 1
  # string: 

# requirements:


test:
  commands:
    - xxxxxx

about:
  home: http://broadinstitute.github.io/picard/
  license: xxxxx
  license_file: xxxxxxx
  summary: 'xxxxxxxxxxxxxx'