package:
  name: geopandas
  version: 0.1.1

source:
  git_url: https://github.com/geopandas/geopandas.git
  git_tag: 0.1.1

requirements:
  build:
    - python
    - setuptools
    - pandas
    - shapely
    - fiona
    - descartes
    - pyproj

  run:
    - python
    - pandas
    - shapely
    - fiona
    - descartes
    - pyproj

test:
  imports:
    - geopandas
    - geopandas.io

about:
  home: http://geopandas.org
  license: BSD
  summary: 'Geographic pandas extensions'
