package:
  name: typechecks
  version: "0.0.2"

source:
  fn: typechecks-0.0.2.tar.gz
  url: https://pypi.python.org/packages/source/t/typechecks/typechecks-0.0.2.tar.gz
  md5: 07501491d2f9e7a67889df15be1b1ea8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - typechecks = typechecks:main
    #
    # Would create an entry point called typechecks that calls typechecks.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - typechecks

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/hammerlab/typechecks
  license: Apache Software License
  summary: 'Helper functions for runtime type checking'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
