package:
  name: samtools
  version: 1.2


source:
  fn: samtools-1.2.tar.bz2
  url: https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2
  sha256: 420e7a4a107fe37619b9d300b6379452eb8eb04a4a9b65c3ec69de82ccc26daa


build:
  number: 1
  # string: 

# requirements:


test:
  commands:
    - "samtools --help"
    - "cd $SRC_DIR && make test"



about:
  home: http://www.htslib.org/
  license: MIT
  license_file: LICENSE
  summary: 'Reading/writing/editing/indexing/viewing SAM/BAM/CRAM format.'