package:
  name: vsearch
  version: 1.1.3

source:
  fn: vsearch-1.1.3-linux-x86_64
  url: https://github.com/torognes/vsearch/releases/download/v1.1.3/vsearch-1.1.3-linux-x86_64
  sha256: 4df3b4b4a31267cec9b7845aea2b68d61f6132762956048b26e4b93967eb5238

build:
  number: 2
  # string: linux_x86_64

# requirements:
#   build:
#     - zlib
#   run:
#     - zlib

test:
  commands:
    - vsearch --help

about:
  home: https://github.com/torognes/vsearch
  license: AGLP3 License
  summary: 'Open and free 64-bit multithreaded tool for processing metagenomic sequences, including searching, clustering, chimera detection, dereplication, sorting, masking and shuffling'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
