package:
  name: vsearch
  version: 1.1.3

source:
  fn: v1.1.3.tar.gz
  url: https://github.com/torognes/vsearch/archive/v1.1.3.tar.gz
  sha256: 1a5af45c6ddb018577c4433fa15c7ab41a216c0e3248bb3c32fd6cb06ced19fe

build:
  number: 1
  # string: linux_x86_64

requirements:
  build:
    - zlib
  run:
    - zlib

test:
  commands:
    - vsearch --help

about:
  home: https://github.com/torognes/vsearch
  license: AGLP3 License
  summary: 'Open and free 64-bit multithreaded tool for processing metagenomic sequences, including searching, clustering, chimera detection, dereplication, sorting, masking and shuffling'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
