package:
  name: pprocess
  version: "0.5.1"

source:
  fn: pprocess-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pprocess/pprocess-0.5.1.tar.gz
  md5: 88cb93ac61968ddb3dbe2a287499fa93
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pprocess = pprocess:main
    #
    # Would create an entry point called pprocess that calls pprocess.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.boddie.org.uk/python/pprocess.html
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Elementary parallel programming for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
