package:
  name: muscle
  version: 3.8.31

source:
  fn: muscle3.8.31_i86linux64.tar.gz
  url: http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz
  md5: 97d2f9bb25e30ed62a6e132d644ed700

build:
  number: 0
  string: i86linux64

test:
  commands:
    - muscle -version

about:
  home: http://drive5.com/muscle/
  license: public domain (http://www.drive5.com/muscle/manual/license.html)
  summary: 'Multiple sequence alignment. Faster and more accurate than CLUSTALW.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
