package:
  name: vcftools
  version: 0.1.13

source:
  fn: v0.1.13.tar.gz
  url: https://github.com/vcftools/vcftools/archive/v0.1.13.tar.gz
  md5: 45368c056b1c3a35c478e1300a5a7eca

build:
  number: 0

requirements:
  build:

  run:
    - htslib

test:
  commands:
    - man vcftools

about:
  home: https://vcftools.github.io/
  license: GNU LGPL
  summary: "The aim of VCFtools is to provide easily accessible methods for working with complex genetic variation data in the form of VCF files."