package:
  name: recipy
  version: "0.1.2"

source:
  fn: recipy-0.1.2.tar.gz
  url: https://pypi.python.org/packages/source/r/recipy/recipy-0.1.2.tar.gz
  md5: 8f5650db8a9494e710fc48681aa0305b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - recipy = recipy:main
    #
    # Would create an entry point called recipy that calls recipy.main()

    - recipy=recipyCmd.recipycmd:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - wrapt
    - tinydb
    - jinja2
    - docopt
    - gitpython
    - gitdb
    - flask
    - flask-script
    - flask-bootstrap
    - flask-wtf
    - python-dateutil

  run:
    - python
    - wrapt
    - tinydb
    - jinja2
    - docopt
    - gitpython
    - gitdb
    - flask
    - flask-script
    - flask-bootstrap
    - flask-wtf
    - python-dateutil

test:
  # Python imports
  imports:
    - recipy
    - recipyCmd
    - recipyGui

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - recipy --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/recipy/recipy
  license: Apache Software License
  summary: 'A frictionless provenance framework for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
