package:
  name: tinydb
  version: "2.4"

source:
  fn: tinydb-2.4.zip
  url: https://pypi.python.org/packages/source/t/tinydb/tinydb-2.4.zip
  md5: f70669dd2c6572075de38d7e3add8487
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tinydb = tinydb:main
    #
    # Would create an entry point called tinydb that calls tinydb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - tests
    - tinydb

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/msiemens/tinydb
  license: MIT License
  summary: 'TinyDB is a tiny, document oriented database optimized for your happiness :)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
