package:
  name: plink
  version: 1.90b3w

source:
  fn: plink_linux_x86_64.zip
  url: https://www.cog-genomics.org/static/bin/plink150903/plink_linux_x86_64.zip
  md5: fbcee164554591c93da5c19838cf37fb

build:
  number: 0

test:
  commands:
    - plink --help


about:
  home: https://www.cog-genomics.org/plink2
  license: GLP3 License
  summary: 'PLINK is a free, open-source whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
