package:
  name: rtree
  version: "0.8.2"

source:
  fn: Rtree-0.8.2.tar.gz
  url: https://pypi.python.org/packages/source/R/Rtree/Rtree-0.8.2.tar.gz
  md5: 4ba7276cbdb4c51b373068004ae864d3
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rtree = rtree:main
    #
    # Would create an entry point called rtree that calls rtree.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - rtree

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://toblerity.github.com/rtree/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'R-Tree spatial index for Python GIS'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
