package:
  name: faststructure
  version: 1.0

source:
  fn: v1.0.tar.gz
  url: https://github.com/rajanil/fastStructure/archive/v1.0.tar.gz
  sha256: f1bfb24bb5ecd108bc3a90145fad232012165c1e60608003f1c87d200f867b81

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython
    - gsl
  run:
    - python
    - numpy
    - scipy
    - cython
    - gsl


test:
  imports:
    - Bio.Seq

about:
  home: https://github.com/rajanil/fastStructure
  license: MIT
  license_file: LICENSE
