package:
  name: gffutils
  version: "0.8.5"

source:
  git_url: https://github.com/daler/gffutils.git
  git_tag: v0.8.5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gffutils-cli = gffutils.scripts.gffutils-cli:main
    #
    # Would create an entry point called gffutils that calls gffutils.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython
    - six
    - argh
    - argcomplete
    - simplejson
    - pyfaidx
    - biopython

  run:
    - python
    - setuptools
    - cython
    - six
    - argh
    - argcomplete
    - simplejson
    - pyfaidx
    - biopython

test:
  # Python imports
  imports:
    - gffutils
    # - gffutils.scripts
    # - gffutils.test
    # - gffutils.test.data

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - nosetests gffutils

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: https://github.com/daler/gffutils
  license: MIT
  license_file: LICENSE
  summary: 'Work with GFF and GTF files in a flexible database framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
