package:
  name: pybedtools
  version: "0.7.0"

source:
  git_url: https://github.com/daler/pybedtools.git
  git_tag: v0.7.0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pybedtools = pybedtools:main
    #
    # Would create an entry point called pybedtools that calls pybedtools.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six
    - pysam

  run:
    - python
    - six
    - pysam

test:
  # Python imports
  imports:
    - pybedtools
    - pybedtools.contrib
    - pybedtools.scripts
    - pybedtools.test
    - pybedtools.test.data

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/daler/pybedtools
  license: GNU General Public License (GPL)
  summary: 'Wrapper around BEDTools for bioinformatics work'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
