package:
  name: pigz
  version: 2.3.3

source:
  fn: pigz-2.3.3.tar.gz
  url: http://zlib.net/pigz/pigz-2.3.3.tar.gz
  sha256: 4e8b67b432ce7907575a549f3e1cac4709781ba0f6b48afea9f59369846b509c

build:
  number: 1

requirements:
  build:
    - zlib >=1.2.6

test:
  commands:
    - pigz
    - unpigz

about:
  home: https://github.com/madler/pigz/
  license: Custom
  license_file: LICENSE
