package:
  name: pyopt     # lower case name of package, may contain '-' but no spaces
  version: 1.1.0    # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  fn: pyOpt-1.1.0.tar.gz
  url: http://www.pyopt.org/_downloads/pyOpt-1.1.0.tar.gz


  
# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 0                        # (optional, defaults to 0)

  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python 
    - numpy
  run:
    - python
    - numpy

about:            # (optional)
  home: http://www.pyopt.org/index.html