package:
  name: bwa
  version: 0.7.12

source:
  fn: bwa-0.7.12.tar.bz2
  url: http://downloads.sourceforge.net/project/bio-bwa/bwa-0.7.12.tar.bz2



build:
  number: 1
  # string: 

# requirements:


test:
  commands:
    - "bwa 2>&1 | grep  'Burrows-Wheeler'"

about:
  home: http://broadinstitute.github.io/picard/
  license: GPL3
  license_file: COPYING
  summary: 'BWA is a program for aligning sequencing reads against a large reference genome (e.g. human genome). It has two major components, one for read shorter than 150bp and the other for longer reads.'