package:
  name: glibc
  version: 2.22

source:
  fn: glibc-2.22.tar.xz
  url: http://ftp.gnu.org/gnu/glibc/glibc-2.22.tar.xz
  sha256: eb731406903befef1d8f878a46be75ef862b9056ab0cde1626d08a7a05328948

about:
  home: http://www.gnu.org/software/libc/
  license: LGPL
  summary: "Any Unix-like operating system needs a C library: the library which defines the ``system calls'' and other basic facilities such as open, malloc, printf, exit..."
