package:
  name: luigi
  version: "1.3.0"

source:
  git_url: https://github.com/spotify/luigi.git
  git_tag: "1.3.0"
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - luigi = luigi:main
    #
    # Would create an entry point called luigi that calls luigi.main()

    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cached-property
    - pyparsing
    - tornado
    - python-daemon

  run:
    - python
    - cached-property
    - pyparsing
    - tornado
    - python-daemon

test:
  # Python imports
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

#    - luigi --help
    - luigid --help
    - luigi-grep --help
 #   - luigi-deps --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/spotify/luigi
  license: Apache Software License
  summary: 'Workflow mgmgt + task scheduling + dependency resolution'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
